const day_03_2 = () => {
    const data = [
        "TZZjzzZLfZbzgzZNNJZjwCVbwMmhwCbBpCMMBCbM",
        "qRQPDqnWFQDtCCBQmQwmGGVG",
        "FPllWPDPrncZsLVrgSZTSZ",
        "RczPzRzvflVwfplrZQglmmJJDGQJ",
        "nFbBWWFZbZtJDjmgmqqF",
        "bnMNZWnWWHTLBBdwcCwcPCwpCSpPLc",
        "CjpMtptpChnpMnCSGjSShMqpTVVWFFTVNVNLmHwmHLTcFnVT",
        "fglsGJsJssBPszvddgTFVTFFFBwwTVVmHVFF",
        "JgJrDgsPfMDhGhCRQC",
        "PSMDSMhwmPwqDMmzrtttNQvNFmFFGFtLld",
        "nRTCCQjcTVJJTVTbggTnFvtNdGdlFbFvbHtWFLNt",
        "gjfTZZCRCnZJjJRRQBCBszDMPppfsPwMzfMqDsSs",
        "LTmnZTgMmbWWGWZQZb",
        "cHCCHHwsPtsHQtWfWjtGlWjbjt",
        "JNQQzzPwwHsRwNSRdnnddqqvSMqMvDqm",
        "CZFNGZfHvgfgZzFZfNfPVJMBrqVhjrrrhvvSjbqv",
        "czlDnlcDWLnlnLQwTbqJqMwqjhVBbhJhJJ",
        "RDQTTWzLWsDGsNHNNgpZmC",
        "rWzbWWMWcrCbfzbwpDrQNqmqNwTNBN",
        "FvsVggVvLGsHQHfppmwTNBfN",
        "VGhsghvZLjPSLshgFVPGFPVJWCtMCJMflJtdJWCMcttljz",
        "bgScSbJwPNqrQLCgLg",
        "BzTsRVGmTDBZBwRVmzGQNZjrMCqLjWrqWNQNnr",
        "GvdRDdzGzdvdDdmTzfwhfFlFPlbfchvlpl",
        "JlqjMtqtSGGZjqSMlmvZZbChRRQbbPhBhCbRBr",
        "dLfzFNVfLLzwznLdFzzwWQBQVBhWbJDrCPVBBBPP",
        "HLgdNddfMjGJJgJt",
        "nZHZDJHLTDnrHrbGpRrRzR",
        "QmsBjdmBmqQzpRbZbp",
        "ttSjjjdWvsFsmBMBfWWMMtwCNCZJvLCnnnJCZcLTvnhN",
        "bbgngMMPfnwPmPgPDPNZMtptHzHtRRvpVHRz",
        "rsWWhJCWqBHBNJNZpvJtzRvF",
        "rWBrjGGsQQWlQcllCDLfwHQTDDgfQPmnDT",
        "lWDFllmGhbWzCglHHlRHMqCq",
        "fBtjwNwfJfZvJJBwBJZjVLNnnnMRVTzgMVVqTLzT",
        "vJQtJrprvrbcdcpmzDDd",
        "bmhbRmhjwddjHMGHnNtHNQNm",
        "nBzVpgFnzVgLpFfHNGqtGfLGGNfH",
        "BTgVVPPSPBSVlTzpzsbWhjWjnhWZlwsWZR",
        "lBQVBBMDTMSTHHCqgLHCzv",
        "ccWcNhtfpFvphspFcttHwwqzmdsCqLgLzLPdLL",
        "tNjFZpnFtJNZJFfjJNpNNFjVbVDMVGRZMGlbQlQrBrbvQr",
        "bRJtJRfRdwRBbwJzhGGcHpwrpCwDclpHDD",
        "hSgnjPVmVVGcWVGWpV",
        "STmFgSnPqQTjNmqJftLszfMqBhdz",
        "WzjrRLWnlRsVRLLwtGmdhNBmbmwN",
        "ZccgcpMfQTpgcpDDvNbtdhhhMGHtdFBNHB",
        "vpDggvPPTvZTfTvpZcPQSZDsqrlrnRGjsrjRCrSlWRljjS",
        "DbZfRRZfPjWDfDntnzggvgMLmVqMMmlLQjFM",
        "NCJCCfBTThBJssSHcgFMlmMvlVHVqVgmLl",
        "rfTJJcJrJdShscSBZbtpnPRDDdnPDRbt",
        "zrTfLGVVLZsrsJcGJVsvQMhdlmMPfjlhlflflbDP",
        "pCWCwRbWBgHlDhPMDPRjjd",
        "pSggBwBCNSbrJLVTTVNG",
        "CNCMSMgQCgQNQhfMGSGSzgfGJhchrHHwBlnJlHPqBBrHwsww",
        "ZVWDptmTtbptpDvZWsPlwblrJPbnHcqnJwrP",
        "pRFtWZVVpVWWZVWtQLzsLQMLzCfFsGgz",
        "MlcpDmgWNlPqcmmqmcgcPdNDRjhLSRRVLjRRShGFjFWRSLLW",
        "bwQJnzbzJTbvMJSHhGGHRjzLGRjR",
        "wZbBwwQvtbtQtBbnvJwbCnwmsMpNcccgDmdPcsqqqsDqCc",
        "zMhMnRbZMpCblpzLlhJPRjDFcQPtJQPcDdWj",
        "mNSGvgdSsBGwwNDvWtQJWjJWPHFF",
        "GmdgGdgfqqNBgVGrbCMhrMfLLflhpL",
        "PVHHPMLMgLQSLLsnHBCZfhzpRfhTpdRppSfdZf",
        "rgmWvWgFrmGlZGGfphhpZG",
        "bJgDFqFcmmWDJWbvJFtMCPQsHPHBVPVCQPcCsQ",
        "VJJHNNmtGqRmMVVwRfTCRfnQpFTFnF",
        "vSvjSvbBzvldhcGwGffFCQCwgrFd",
        "jLhhlGjvczDhLSlDWjLzctHMZtJtHmqHJZqWmVsMqW",
        "LhchvRJtHzhdTTdJjQLQjQVVnjSmLMLQ",
        "NFpClSPqwqNgPPNPNglllrBQBrQVjQjmBQnfBfjQjC",
        "wWGGpSwSZNpNPFDwPDDhzDdvbvJzHHJbhtzv",
        "gtFtNNmlGzQtNPttfDMwwfbbMR",
        "LVcBjsBjFJrLFWVrBrMbbMSSPpDPPqVDfpPb",
        "JrCBnsdWJJrHZdFmGglmmg",
        "BmCCWSLmWsmtCCSppSmmpcpRfMZjjBgJJGGjBwZfgjZjFwJw",
        "TPTPnTPrPVvQTTzTVdPMrJJZwggjfHwJJgjHZrJFwH",
        "NQvvNnQPDPhNcstcStDMWWWS",
        "hntthHVQVbbbSzgjgZjngjRD",
        "TTvJJCldFJTvFFTBFlpTzvvsRgZWGWSLGrlWWRSGLjRGjRDL",
        "TzCcFcvcsCmqPMQwQPcwPM",
        "DltVvVLvbGPDhjRhhjSZjSSL",
        "CffszNzssHCCqJjJnqRnpgRpZB",
        "CszNWdsfDWtZwwDG",
        "DdbmddmzDDNbsqzvzmdzsdsRJLjqtVWWjWJBBVBwVjWJtB",
        "CnFPCcCcPFFFGffjjCWBVwwtRwNwCw",
        "QNZlphpNDpHsDrvg",
        "gdHSCbCTGgQbtNLvgrjwNMMwrr",
        "BnzVRHFZVHvNhNRNMMhW",
        "zFzFcnlZPHlbQdlT",
        "GmddjTrgFgmgWGmFvmmmFFfwSCVpwHVrHpwhwrpCBfBC",
        "tctRcRRCMtsMsMDPlDtDbMzbQJJbhwHVQJhBHJVQHBbpfB",
        "tPDDtcnRRqzzcCzLPMLPRddWTdqgdZqZTZqdGmjFWv",
        "sWvfGlGqsSggNcNcmf",
        "JBwwVccFJtrzpMwtrMMMLTnNnJngJgQNSgmTJgLN",
        "wtPMHrRrBwtPVRHrrHVPZvqDWWWcsGsvqDlZZd",
        "jBjBBJRhCJbjffCjWlDfmbFQmZFgPpmmgpmbSSQF",
        "dsqGrttGhswQmqpFFqQw",
        "THdsdrdTHzLLdLTsTdtHNshlDffDCHJDjfBcBRlJRfjV",
        "lDNlPBQlccQttcNBcDPvFFJmdTwtFJFdTdFgzg",
        "bCWMLfpZLZLVhMbGLLsVzTwmhvTgSJHwHdTvSFSwJJ",
        "RCZZVZLZWLRZpZsfpVsscjzQRRPQcPcDQzPljzPB",
        "tVfCLfRVCGTRCPtRMPftHGqpnnqpdzqNbHGdqzHd",
        "DlDlWmvDWsWJmMmmsWvWDlSHzHpnpbNqnbnrppbbpprJdd",
        "DvhWDFBhvslFSDFPVPVBfgwgfCtMLV",
        "FtlLQqlDnMmFJRPM",
        "hwlpwBphHplpdHfZnjRRjMmCgfPZgJ",
        "BdpwvzcNpBrDbLTslszG",
        "RjPhcnNzRcLcFlsFNlFRfTffdhJhSTVqqSdDMVMf",
        "ZWtZgrgPCvrbHSSfMqJTDWpdMf",
        "vBvHgCmgHtgvtrHbwcLjNLNFcnPBNcPLQQ",
        "FZhtMtddjCGQSVjmjC",
        "qbvcnvPqBWcPVVCTCmSQLVCq",
        "vVBVzBNpDNhgdZDg",
        "lNVtllQFQVnQNrZpCtQCdZZjSbfRbcDjZqSfTqDffJ",
        "HzBJBvPJLWHvwmBwHWRsbsqfbSbzbTbTTRDs",
        "vLwPHLLMGHwGBWBHLvBgBVCgrQQpdprNVttQJrpQdQ",
        "TbZDQlZDCHjwtbjnRSTRTPPTBWWWPB",
        "GhpgpLJFcvgcMRqfBBmSQggzWq",
        "LcFQpGdGsrjDDDHssl",
        "qzpPgTpnNWRfTBBCWf",
        "rLFsVcFltVBfdGClPdGf",
        "vmtZvwsZrLFFFrPDqzDvjzDqJMjv",
        "lDlzzsMPDssjsSGTjlTTsqbbftfqNwJNfHqqbfDmbW",
        "FFgpFndhQLnhnLRpQCLnVrgtHttvfqJmNbqWWbJHNHtb",
        "pBFrVVrmZGSBBZsz",
        "bGMfcMCPPCtcLqPLCRqPZnjLVTdnjjWsVLHVlllVVL",
        "SwzDBmzgwFSFQzvgBrgvwFdVHjHwWHJsjnVsTWVHHWHJ",
        "FFrBNpQWpFrgFSmmSpQmrQQNZPPRRbfGMqCGcCPGtMqqcZ",
        "PBhcVpBRPcqHfnjRRJJl",
        "GsMrsGTszsrMdnsGZmzMsCfDtvHfHqvjJlvdqfHflvtq",
        "gmrGMGGmGgbmsrrCThnBFSQSFVFhSnVcpg",
        "QCDnqdqVPswpJZMLLCHZMJ",
        "RhchlRBRWlLmZzVWVJGV",
        "VrhfhhBgTcRTVhdDFwdwqTDnnnjw",
        "jVsSsLjJJmSLlmJSlPthrhHZGthLpZLdWZ",
        "nqFTFNbRfnDCRzfnzqPBpGcdGHttWHdcZGRrtchh",
        "bqNzTTbFTnwnTmPjvwsVgQVjgl",
        "BBlNWWMlVWQlLPNjVLWWGMQcJCscFSmwRCSnCFJscwcw",
        "bbHZHvHpHgrqSCcwvSsFFRsv",
        "wwbhdfdwZlWljdtNdW",
        "NmlnhSNwzjjswNvqqqbjgddqtgVt",
        "TQMTMrFJHDFTFBrTMDMQDQgdnCVggtpLpvggnQdvdQ",
        "fJPJHrFZFBHTDPrTJHZrFswsWnWGmmGNlwwlRsmSZN",
        "bdntqdNMQCtcnnbqtNtcgQWWjjFDjhSBSjJDWSfDFWBc",
        "RwsZzRvZQPQsGPWjphzpfjfBffzf",
        "GPsrRQvvQlwlMnHHlTgMNT",
        "TnnnQTLnBPQMRMpgGRLGwp",
        "VNcvvjjVczRRjsZvvqgmpMGwZWZmJSqwwW",
        "tzvsdrsVdFndRDbdbC",
        "qSfbWlZVPdWmmcjvjjwrcwQm",
        "TpTTpPJzTBnNsshnnTsctLwjvQMzrLrjjFMtjv",
        "NPsNBhNJhBJgNnqSSZlSdVgVGqdq",
        "pQsgcsdSpmsJctQhrhqDHPjrjNQH",
        "VVGGbfvvMMBZPjjHqVVrTjmC",
        "fZbfnRLBfbZGblbfMZnBGZFlzJcRdttwtJtdzmdswcJJdpRs",
        "TDqDqTZFFqDqdDvSMwtCbjbFjbmGGwCffG",
        "hQQnchQZpQzCfmGtblfLhw",
        "RnNpRPrcpsRsVWHSDZSqWrDJ",
        "gLqgTfgwTCwmgWWrfCcRdvBCGGBZjGRvvZ",
        "MFbPMPnNzFbssQFpQNNScQSdjvBBBSRllBvZvc",
        "sHMHpzsJnpNMNnHsnMJbWLVwmwgVwDdDJwgDffrJ",
        "QGdbSLSzBVbGRQrJfllDbnfpJfltJl",
        "ZMwPCFPwPmFgCFvZgZmcFwcPhJnphhscQnJhJnsptnDNthts",
        "PHZgCmwggvMjZFWjFvQTBzRGHqSRRTdRVGGQ",
        "zJRppmjPMCjJgtBQWtZZgPtg",
        "tTFsltFtVGWnllQBnn",
        "swLfbFSvsmJCCSRCRt",
        "MZVRQzMwfRQgQQDvncrvrSHHdSfS",
        "tWWBhJbhnBsWCWCGdDbvSpvDpcrrcqHq",
        "NBTCBJsCTFJFjzjFMwnzLR",
        "RBhlNZsgrZNdbfrrmFGbjb",
        "ztJLFLzLQDtnnCLLCzSTwzJmqmGGjddPmSPPmGjpdqGMPj",
        "JcLLFVtLJDTQCsZgscvlWBZHgv",
        "hznggMvgwwPCDwhnCMWsDlHjtJPjtjrZlljtPJjZHt",
        "mvvGVVcvHJtppGpS",
        "bVQvQLfRRbfFFwhMsFshsqsFzM",
        "BBRWFZHWSGRZvQtQRpRtHHBjTTcqhzfnBcfzchjTTnhncT",
        "PbwdVMbmlDZmNPTfjrcfnzjf",
        "sMVLmsdmldLVmJLCDHFgSJgZSSGHtFppFZ",
        "SGwFSCvtwjjDvDGDCjjDCNRnzbbnpnBppHBNhbbTpqbB",
        "rBBllQlgslmnmbzqRm",
        "scQsLMZsPMVfMrFwBZtvvCWFtJwS",
        "nlhLFFSggjMnLnLHTPlMTSBfRzrMQBCBCRDDdCdQrzWr",
        "ZwFcssmNJqNNcZGFzdBrRZCDCdCffDrR",
        "mwbwGNcwwpSjPlFgpPlH",
        "HsvNvddbZJDDsNbDqvsqNsqnjtllczmjjbBjzjQzjlncnc",
        "VTCTPGhpwGLfChfGCpTrnrgQrlntrQGQcrcgQr",
        "WpPfLTPWPhMPhwCNdStvSdWHHWHDdH",
        "hjtjnnbLMCwCMhbgfJpfDZpSsGHDHNSmsf",
        "BqBQBccqFrWcPTWdWTcHHNHJpsHpmDDsHHSFSD",
        "QRcPzqWzzzrdzzWvTqQcBcRgnhmhmCbnhtvMmggbLLgLvg",
        "zdTNLLdRdTPFFJFllQSzwJ",
        "mhmBmBBjtjhHmjvvBhvthThnFwQwwSnWbGwlQbQtnnGJtS",
        "cTvHTgjCmVHZgHvhHHdRfMddfLsrRfZNpsPL",
        "lfLnsHhHJBBfBGrBpS",
        "VPjqqwVVqNjqQVVCVPNNVQpGpmppcBcDmGmpsmsDsCrD",
        "QdQNFwQdvjvRqFFqvRPqLgngshhRJsLnHLWgLRhh",
        "dwRwQVNwwJQNnnhmBtZZdCZhFBrP",
        "MMHTvMjsWlmhhBrrrlhm",
        "jWTcWWDWsWMTgjMGsHvGGMsnJzVNpRQQDDpbJVbnnwNrnV",
        "NcRvJCGnWnNMwtMPlMMF",
        "rqRLrVmTrjjRmBqjQLrjzZgMgDHltVPMgFbMFDbPwMwH",
        "fzjrZQSQzBjnvfnsJcGspR",
        "fHPFZPsmffftTpsTqJGhhDjC",
        "bbBdcbcwNGzzbNdBdcNQqJDDTJhDCNjQpRRCJT",
        "VcWBbgBMWbMdzPmPtGWZmLWPFv",
        "zDWFvgCCvWDgVVmrZppPbCPZ",
        "wdqsBhcMdbJJmlBgHg",
        "hTwTQgLNMTsQstjzvSTTWjvfRW",
        "vGGwWsvjpsCShrjTCCrj",
        "CmMCZCtqzmMzNgZgdZzSrzPFrThnrPPHTcrSnH",
        "VVMtQZdgZqLtqLZVMffwwDRCLGWlCsJvwpwlRv",
        "fJfhpVVzMpgczZSqSSnZ",
        "NvPNvRsmNCRsbsvNbhjqgcDZSqSFFmgGGnZZDg",
        "TChvRBBRPsJLTMHMQfwV",
        "CvNPsrfrjvwwfsjwsrNlgDzzBmgmNhlNBHgg",
        "JVmdMJmcMTSqVlnlnnzBHBGg",
        "SmLqSSWqbcbbWqJqqFcTJfPwPwtwWCfrrPrsQvQZZf",
        "hMRnnvfRntfvcGqccDqhHlSLSgjGLWlLHlWPgWPS",
        "bJsssbJFCZsQCsdQFzJWwSPSdSgdWwvwmHWWmj",
        "QBQbTzFzrrzTTtfvffcfqTDM",
        "fdcRNRvdNwczRFLcvNvzRvDSjhlmhclShjSnmMlSmDSS",
        "VtJqbCqqVCfQqVpJHqZfmGDhgmjlMHmDllmggShG",
        "qqtqTpVqJpVPZbffWTNfwzvRrFLL",
        "mmhccmZGNcNhWNmDDGCmvlLWjpjbJRSpdrnzzbRzSjLJpJJz",
        "BQHBgtZQqwTTtfndpSJJbJfbjjRp",
        "THFVBZqQsqTgwtswWWlMclMDNlNclVVM",
        "GPmLbhQmDbbDHfpCQCfdCfTr",
        "SlWVScMgpzFSjgSMtBjTrNNdrfjrHrBd",
        "ZzzsWWnzWFcsRqpJmPhqsw",
        "cfNQdfdRcNHNFcqRcqqdWmLQgMwwMssLggpLLsmm",
        "rTtGGhBTJSThwssmgssGzpHC",
        "VbTTlJvVHbBJthtVbrJRdFnjljqZdfPqPnRdFN",
        "tLtpstBLtzPnQBtFBtMpnpQPhmGGRRhMhGNRRCCmRJmmbvNJ",
        "ffflfqqVVHllVHDVNVZHlTDGSGbGSvhmvTRCCSTjShShCv",
        "DldDlZgWcDdfDZggfddccsnzLWsnNwPFQzPBwLwzzF",
        "FpRCrNpMrCpNRZCrsCpZrCpqvmJnvnLPBwfvfmvzBJnwswBw",
        "DbbVStQgdbJmLbJm",
        "SHlSShlhSHHWcWlghFMNqcRqcZrFpFppTJ",
        "QFPnsjqjtQPWfCZZlZbT",
        "dwrMzzWRVWJVDDlfDlrfDlhl",
        "BNzVdLWwRNmzwWBRVBVzSQQLtnnqSqssFvtQFsjL",
        "TGfDmTcCMMmDsCspRbCCbsMJvWPvSSjZSwhFwwFgjPJZwG",
        "NNHLHBNHrgVFFjJwFJZLhv",
        "BzzqQQnVtrdnVNrtVNBlppbbDCRmdfggRCgmTscf",
        "rmbcvbRbzrsZZCCNQjwdgRGjwGQGLVML",
        "htDnDtHWnWPjVHQdgdNwHg",
        "PFFTlhllffsNsscl",
        "hFSlSlShLppwNlwH",
        "fjSvvfbzBfDjPQvBDqjfsBGdwwLppMHmmHHHbNNwGnmG",
        "SqzVBZDPPDQVFWgrWJTtCg",
        "ghlqSlFhCFRgFsssSqjhlsVsvNPtcNdndctVzdzJPndQPnJd",
        "TwfBmZmLwLZDfWZTbGQPtvzJzdLNcLdrQrcL",
        "GmGwDbZHbmpBmwBWmGDCpvShClvSjgMjRpMqjv",
        "vDDQpzjbqDQDmJvmRFBgNdWcQtdcHcctWcdN",
        "hTfsLlSMCCSCfGCPlhfnGtgBcBHBdgLdVttvNtBBdg",
        "lZvlfPffnZSnMzDjzzmZzDbwqq",
        "cwgNgWWNccLcHnLGnnHD",
        "JRrPNPNlGHPDtzLv",
        "jmBJljNljRZZbpQZBgZp",
        "WWcWLtwHcHLwWRwPWDwZGrCMvvFvZnDrvF",
        "JVVmdbZmCvzGCvzm",
        "ZQgdjVgdjQhJZQbhblbNQqjJLsPSsppscPPWhhWtSctpHsHs",
        "fZtsGZsQQtpFrLqZrLQGZfHmdBjSMNmmRNddbFcMcbmBcc",
        "vnwnlhlTWllgnJVTTgDTnvTwdcjSbRdbHMdcMMNdVdBNjRHj",
        "zDvHnPvTwhnDDCZpLLftqzffst",
        "hdCvWvQQlvlZzgCcGgjCPSLC",
        "HMTHMDRRtmBNtTRDrRmmPcjGPPrdSzcLjjzdfzzL",
        "tqMsNmmVMTNmtMHbZbnJdblZnlwWbV",
        "bzQNPzMbVrfPfLrjrj",
        "ZvZnzsTmnlnTWnJTvSHSsJDvBrdwwwLBtjrBBRtjwHqqrfLf",
        "zpWDWSnnTnJmDzSMNchQcGNMQpQGGN",
        "McCNssGmscnNmmsNzLwwLTSTRBJBBZLFTz",
        "WTbhQbfPvWThFwFWJHBZWwLH",
        "jThbtbPjvDDvDhqjppdcsgcGGcMmNlNldtNt",
        "VsRLrPMPrrNRRDMDNsDMRdGCdGGZZZwljjCCjHCHQwcG",
        "qhmfBgtqlfqzfTtggSWwbHjcwGjjbwwcTQCC",
        "lnSfStzhvfvzFgvqsLJLrpPpFsRsMNPP",
        "mFfWmmTbcFNFZWbcCftLCsCLGLfCGqGV",
        "DQQMlJhjGqtswZDD",
        "BpBhQSSQRSljRJRvQllnTWNHrWccHrNppbNZWp",
        "llSWcPmCDRCSmjPTCCSPHtLrfJnwrJfVBRfJwrqB",
        "FFFgdFdpGVHtVGwBtn",
        "gMbbsNdvbsQgppppvvszvzWTTTlMCnlPDjTlDCWWccmC",
        "fzMlGqVMwzSSPNRBrRZrFrFRGZ",
        "blnlQnlWFZbmFbHr",
        "CgttsQpstcCtnslqfjhPhVzMgMPz",
        "SrSHtjrJQZjBpvNctmnRvnDm",
        "GWPlhPqFfPsGwCqsnsGszWGwNdMLpRvLmRNcNpmRmvDfpMLM",
        "GPCWWWzbbzqPnnCbPZHbQrQrQgVBVJJVJV",
        "ZVhCwqvFZVpwdhLdqLhtvcGBcSNLRSRBGRBNGNSSmN",
        "lTjnlnjgslsjJTgrMrQQjjTSGSpcGRSmDBNSNJcDSBbRmS",
        "zMrjllgnPrlrnlWrQgTgzgvwqpFwZHChHvPwCtVptCVt",
        "RTjjznsTsnnrzRrmTmrNNCMhwMrCNNCwWhCMGN",
        "DvScpDDVfBPqVcSbDpbfHpqwCWGJCwCJhvFdFFwlMGJWCG",
        "fhHPbhZSpDbDTmsTZTjRzzQz",
        "QbVQvNrrdFcbcMvvdNrcGrrczPnPplPnfnpzwpgmlflRVwwP",
        "jBHLRqZWtLLqWDhBLshBCLsHgpfftfPmmpfpwnwfwJgfpfPn",
        "WCRhsLDsDLBChTLWHChFTTMdGTQGvGQcMQNGMd"
    ];

    const run = () => {
        const alphabet = [
            ...Array.from(Array(26)).map((_, i) => String.fromCharCode(i + 65).toLowerCase()),
            ...Array.from(Array(26)).map((_, i) => String.fromCharCode(i + 65).toUpperCase()),
        ];

        const lines = [];
        for (var i = 0; i < data.length; i += 3) {
            lines.push(data.slice(i, i + 3));
        }

        let sum = 0;
        for (let i = 0; i < lines.length; i++) {
            const line = lines[i];

            const elf1 = line[0];
            const elf2 = line[1];
            const elf3 = line[2];

            const priorities = [];

            for (let j = 0; j < elf1.length; j++) {
                if (elf2.indexOf(elf1[j]) < 0)
                    continue;

                if (elf3.indexOf(elf1[j]) < 0)
                    continue;

                const char = elf1[j];
                const priority = alphabet.indexOf(char) + 1;

                if (priorities.indexOf(priority) < 0)
                    priorities.push(priority);
            }

            const sums = priorities.reduce((a, b) => a + b, 0);
            sum += sums;
        }

        console.log(sum);
    }

    run();
}

day_03_2();
